### ISSUE TITLE
이미지로 다운로드 시 에러 발생

### ISSUE THREAD

**Issue by SeYoungCho-SLDT** [sex-request/frontend#75]
환경: 페이스북 브라우저
예상 결과: 신청서가 이미지로 다운로드
실제 결과: 에러

**Comment by ChoSeyoung** [comment]
참고 이미지 올려드립니다.![image](https://user-images.githubusercontent.com/42459067/139872574-cc3b9601-7042-4842-93c4-8a366f4a08c2.png)

**Comment by juunini** [comment]
제보 감사합니다!
재현은 안되지만 다운로드가 페북 브라우저에서 실제로 일어나지 않는 상황도 생기고... 여러모로 문제가 있네요 ㅠㅠ

이걸 해결하기보단 회원가입을 구현해서 이 기능이 불필요한 상황을 만들고 싶다보니

페이스북이나 트위터등의 인앱 브라우저에서는 동작하지 않을 수 있다는 경고문을 넣는걸로 대신 처리하겠습니다.
