### ISSUE TITLE
이미지 다운로드 시 알수없는 문자 생성

### ISSUE THREAD

**Issue by naninyang** [sex-request/frontend#76]
![image](https://user-images.githubusercontent.com/6149100/139873330-719a25c0-7af0-40c0-8442-879f5c23ef5d.png)

Test Env. iOS 15.0.2

**Comment by juunini** [comment]
제보 감사합니다 ㅠㅠ
아... 얼른 로그인 붙이고 이 기능이 필요 없도록 만들어야겠네요.
여기에 시간을 쏟을 순 없으니 일단 크롬 브라우저에서만 제대로 동작한다는 팝업을 띄워야겠어요.
