### ISSUE TITLE
Image 다운로드 시, 토끼 이미지가 사이즈가 맞지 않습니다.

### ISSUE THREAD

**Issue by mingkyme** [sex-request/frontend#80]
![섹스신청서 (1)](https://user-images.githubusercontent.com/45954551/142749107-576c0eb6-772a-4206-9472-e89c4838cc4a.png)

사이즈에 대해서 조치가 필요해 보입니다.

**Comment by juunini** [comment]
요즘 너무 바빠서 이슈가 올라온줄도 몰랐군요 ㅠㅠ
곧 수정해서 배포하겠습니다.
감사합니다!

**Comment by mingkyme** [comment]
토끼 이미지 URL
https://www.sex-request.app//_next/static/media/logo.678309ec.png?auto=format&fit=max&w=128
이렇게 돼 있는데

https://www.sex-request.app//_next/static/media/logo.678309ec.png?auto=format&fit=max
w 쿼리만 지워도 정상 동작 확인되네요

html2canvas과 충돌이 있는 것으로 추측됩니다.

**Comment by juunini** [comment]
a0b050d 커밋에서 완료되었습니다.
